name: Update Questie Cask

on:
  schedule:
    - cron: "0 12 * * *" # Daily at noon UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run update script
        id: get_release
        run: bun run .github/scripts/update-questie.ts

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git diff
          git add Casks/questie.rb
          git commit -m "Bump Questie to v${{ steps.get_release.outputs.VERSION }}" || echo "No changes"
          git pull --rebase
          git push