name: Update WoW Classic Addons

on:
  schedule:
    - cron: "0 12 * * *" # Daily at noon UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run update script
        id: update
        run: bun run .github/scripts/check-for-addon-updates.ts

      - name: Create Pull Request
        if: steps.update.outputs.has_updates == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATES: ${{ steps.update.outputs.updates }}
        run: bun run .github/scripts/create-pr.ts
