name: Update Questie Cask

on:
  schedule:
    - cron: "0 12 * * *" # Daily at noon UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run update script
        id: get_release
        run: bun run .github/scripts/update-questie.ts

      - name: Publish Update
        if: steps.get_release.outputs.VERSION != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b automation/update-questie-${{ steps.get_release.outputs.VERSION }}
          git push --set-upstream origin automation/update-questie-${{ steps.get_release.outputs.VERSION }}
          git add Casks/*.rb
          git commit -m "Bump Questie to v${{ steps.get_release.outputs.VERSION }}"
          git pull --rebase
          git push
          gh pr create --title "Bump Questie to v${{ steps.get_release.outputs.VERSION }}" --body "Automated update of Questie to v${{ steps.get_release.outputs.VERSION }}" --base main --head automation/update-questie-${{ steps.get_release.outputs.VERSION }}
